/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EnquiryModal: typeof import('./src/components/EnquiryModal.vue')['default']
    HeroSlider: typeof import('./src/components/HeroSlider.vue')['default']
    PropertyCard: typeof import('./src/components/PropertyCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhatsAppButton: typeof import('./src/components/WhatsAppButton.vue')['default']
  }
}
